# -*- coding: utf-8 -*-
"""Copy of shifa_internship.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ONNJOaBhJ-aJp6E5QyeFXGFEZOvCc8xy
"""

# ==========================
# Q1. Menu Function
# ==========================

def menu(item):
    if item.lower() == "karhai":
        return "Karhai is cooking 🍲"
    elif item.lower() == "biryani":
        return "Biryani is ready 🍛"
    elif item.lower() == "bbq":
        return "BBQ is grilled 🍖"
    elif item.lower() == "chai":
        return "Chai is served ☕"
    else:
        return "Item not available ❌"


# Testing Menu Function
print(menu("karhai"))
print(menu("biryani"))
print(menu("bbq"))
print(menu("chai"))
print(menu("burger"))

# ==========================
# Q2. Customer Serving System
# ==========================

print("\nCustomer Serving System")

for i in range(1, 6):
    item = input(f"Customer {i} ordered: ")
    result = menu(item)
    print(f"Customer {i} -> {result}")

# ==========================
# Q3. Karhai Spice System
# ==========================

def karhai(spice_level):
    if spice_level.lower() == "high":
        return "Very Spicy Karhai 🌶️🌶️🌶️"
    elif spice_level.lower() == "medium":
        return "Normal Karhai 🌶️🌶️"
    elif spice_level.lower() == "low":
        return "Mild Karhai 🌶️"
    else:
        return "Invalid input ❌"


# Testing Karhai Function
print("\nKarhai Testing")
print(karhai("high"))
print(karhai("medium"))
print(karhai("low"))

# ==========================
# Q4. BBQ Platter System
# ==========================

def bbq(pieces):
    if pieces >= 10:
        return "Full BBQ Platter 🍖"
    elif pieces >= 5:
        return "Half BBQ Platter 🍗"
    else:
        return "Small BBQ Plate 🍢"


# Testing BBQ Function
print("\nBBQ Testing")
print(bbq(12))
print(bbq(7))
print(bbq(3))

# ==========================
# Q5. Chai System
# ==========================

def chai(sugar):
    if sugar == 0:
        return "No Sugar Chai ☕"
    elif sugar == 1:
        return "Normal Chai ☕"
    else:
        return "Sweet Chai ☕🍬"


# Testing Chai Function
print("\nChai Testing")
print(chai(0))
print(chai(1))
print(chai(3))

# ==========================
# FINAL TASK
# Desi Restaurant Management System
# ==========================

print("\n===== Desi Restaurant Management System =====")

for i in range(1, 6):

    print(f"\nCustomer {i}")

    item = input("Select item (karhai/biryani/bbq/chai): ").lower()

    print(menu(item))

    if item == "karhai":
        spice = input("Enter spice level (high/medium/low): ")
        print(karhai(spice))

    elif item == "bbq":
        pieces = int(input("Enter BBQ pieces: "))
        print(bbq(pieces))

    elif item == "chai":
        sugar = int(input("Enter sugar level: "))
        print(chai(sugar))

